theme: jekyll-theme-minimal

title: HyperGate
description: "A fast, stable, secured proxy software"
url: "https://www.hypergate.io" # the base hostname & protocol for your site
baseurl: "/"
show_downloads: true
cover: "/assets/cover.png"
logo: "/assets/logo.png"
